FROM alpine:3.21
LABEL org.opencontainers.image.source=https://github.com/aicacia/rs-object-storage

WORKDIR /app

ARG TARGET=x86_64-unknown-linux-musl
COPY ./target/${TARGET}/release/object_storage /usr/local/bin

ENV RUN_MODE=production

CMD ["object_storage", "-c", "/app/config.json"]
