replicas:
  min: 1
  max: 16
  resource:
    cpu:
      utilization: 80
    memory:
      utilization: 90
  scaleDown:
    stabilizationWindowSeconds: 30
  scaleUp:
    stabilizationWindowSeconds: 15

image:
  repository: aicacia/object-storage-api
  tag: latest
  pullPolicy: Always
  hash: sha256:41dc5087ec321069388b13f6f84535367df94b8691fe63fd043ba8832afbeb8b

env:
  DATABASE_URL: "sqlite:/data/object-storage-prod.db"

config:
  objects_dir: "./objects"
  server:
    url: https://api.object-storage.aicacia.com

persistence:
  sqlite:
    storageClassName: linode-block-object-storage-retain
    resources:
      requests:
        object-storage: 10Gi
  objects:
    storageClassName: linode-block-object-storage-retain
    resources:
      requests:
        object-storage: 10Gi

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: api.object-storage.aicacia.com
      paths:
        - /
  tls:
    - secretName: api-object-storage-aicacia-com-tls
      hosts:
        - api.object-storage.aicacia.com

resources:
  requests:
    cpu: 15m
    memory: 184M
  limits:
    cpu: 250m
    memory: 512M
