apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "storage-api.fullname" . }}-config
  labels:
    {{- include "storage-api.labels" . | nindent 4 }}
data:
  config.json: {{ toJson .Values.config | quote }}