apiVersion: v1
kind: Service
metadata:
  name: {{ include "storage-api.fullname" . }}
  labels: {{- include "storage-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "storage-api.selectorLabels" . | nindent 4 }}
