/*
 * object-storage
 *
 * Aicacia Object Storage API provides blob services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;
use std::borrow::Borrow;
use std::pin::Pin;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use hyper_util::client::legacy::connect::Connect;
use futures::Future;

use crate::models;
use super::{Error, configuration};
use super::request as __internal_request;

pub struct P2pApiClient<C: Connect>
    where C: Clone + std::marker::Send + Sync + 'static {
    configuration: Arc<configuration::Configuration<C>>,
}

impl<C: Connect> P2pApiClient<C>
    where C: Clone + std::marker::Send + Sync {
    pub fn new(configuration: Arc<configuration::Configuration<C>>) -> P2pApiClient<C> {
        P2pApiClient {
            configuration,
        }
    }
}

pub trait P2pApi: Send + Sync {
    fn p2p(&self, ) -> Pin<Box<dyn Future<Output = Result<models::P2P, Error>> + Send>>;
}

impl<C: Connect>P2pApi for P2pApiClient<C>
    where C: Clone + std::marker::Send + Sync {
    #[allow(unused_mut)]
    fn p2p(&self, ) -> Pin<Box<dyn Future<Output = Result<models::P2P, Error>> + Send>> {
        let mut req = __internal_request::Request::new(hyper::Method::GET, "/p2p".to_string())
        ;

        req.execute(self.configuration.borrow())
    }

}
