/*
 * object-storage
 *
 * Aicacia Object Storage API provides blob services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;
use std::borrow::Borrow;
use std::pin::Pin;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use hyper_util::client::legacy::connect::Connect;
use futures::Future;

use crate::models;
use super::{Error, configuration};
use super::request as __internal_request;

pub struct UtilApiClient<C: Connect>
    where C: Clone + std::marker::Send + Sync + 'static {
    configuration: Arc<configuration::Configuration<C>>,
}

impl<C: Connect> UtilApiClient<C>
    where C: Clone + std::marker::Send + Sync {
    pub fn new(configuration: Arc<configuration::Configuration<C>>) -> UtilApiClient<C> {
        UtilApiClient {
            configuration,
        }
    }
}

pub trait UtilApi: Send + Sync {
    fn health(&self, ) -> Pin<Box<dyn Future<Output = Result<models::Health, Error>> + Send>>;
    fn version(&self, ) -> Pin<Box<dyn Future<Output = Result<models::Version, Error>> + Send>>;
}

impl<C: Connect>UtilApi for UtilApiClient<C>
    where C: Clone + std::marker::Send + Sync {
    #[allow(unused_mut)]
    fn health(&self, ) -> Pin<Box<dyn Future<Output = Result<models::Health, Error>> + Send>> {
        let mut req = __internal_request::Request::new(hyper::Method::GET, "/health".to_string())
        ;

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn version(&self, ) -> Pin<Box<dyn Future<Output = Result<models::Version, Error>> + Send>> {
        let mut req = __internal_request::Request::new(hyper::Method::GET, "/version".to_string())
        ;

        req.execute(self.configuration.borrow())
    }

}
