/*
 * object-storage
 *
 * Aicacia Object Storage API provides blob services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Errors {
    #[serde(rename = "messages")]
    pub messages: std::collections::HashMap<String, Vec<models::ErrorMessage>>,
    #[serde(rename = "status_code")]
    pub status_code: i32,
}

impl Errors {
    pub fn new(messages: std::collections::HashMap<String, Vec<models::ErrorMessage>>, status_code: i32) -> Errors {
        Errors {
            messages,
            status_code,
        }
    }
}

