/*
 * object-storage
 *
 * Aicacia Object Storage API provides blob services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Health {
    #[serde(rename = "db")]
    pub db: bool,
}

impl Health {
    pub fn new(db: bool) -> Health {
        Health {
            db,
        }
    }
}

