/*
 * object-storage
 *
 * Aicacia Object Storage API provides blob services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct P2P {
    #[serde(rename = "api_uri")]
    pub api_uri: String,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "tenant_id")]
    pub tenant_id: i64,
    #[serde(rename = "ws_uri")]
    pub ws_uri: String,
}

impl P2P {
    pub fn new(api_uri: String, enabled: bool, id: String, password: String, tenant_id: i64, ws_uri: String) -> P2P {
        P2P {
            api_uri,
            enabled,
            id,
            password,
            tenant_id,
            ws_uri,
        }
    }
}

