/*
 * object-storage
 *
 * Aicacia Object Storage API provides blob services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadResponse {
    #[serde(rename = "written")]
    pub written: u32,
}

impl UploadResponse {
    pub fn new(written: u32) -> UploadResponse {
        UploadResponse {
            written,
        }
    }
}

