apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "object-storage-api.fullname" . }}-environment
  labels:
    {{- include "object-storage-api.labels" . | nindent 4 }}
data:
{{ toYaml .Values.env | indent 2 }}