apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "object-storage-api.fullname" . }}
  labels:
    {{- include "object-storage-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "object-storage-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config-environment: {{ include (print $.Template.BasePath "/config-environment.yaml") . | sha256sum }}
        checksum/config-config: {{ include (print $.Template.BasePath "/config-json.yaml") . | sha256sum }}
        image/hash: {{ .Values.image.hash }}
      labels:
        {{- include "object-storage-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "object-storage-api.fullname" . }}-environment
            {{- if .Values.envSecret }}
            - secretRef:
                name: {{ .Values.envSecret }}
            {{- end }}
          volumeMounts:
            - name: config-json
              mountPath: /app/config.json
              subPath: config.json
            {{- if eq (include "object-storage-api.is-sqlite" .) "true" }}
            - name: sqlite-pvc
              mountPath: {{ dir (include "object-storage-api.sqlite-path" .) }}
              subPath: {{ base (include "object-storage-api.sqlite-path" .) }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-json
          configMap:
            name: {{ include "object-storage-api.fullname" . }}-config
        {{- if eq (include "object-storage-api.is-sqlite" .) "true" }}
        - name: sqlite-pvc
          persistentVolumeClaim:
            claimName: {{ include "object-storage-api.fullname" . }}-pvc
        {{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}